version: 2.1

orbs:
  node: circleci/node@4.7
  aws-s3: circleci/aws-s3@2.0

jobs:
  build-next-app:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
      - run:
          command: yarn run export
#    - aws-s3/copy:
#        from: build/
#        to: s3://marksheehan.net
#        arguments: --recursive

workflows:
  version: 2
  build_nextjs_app:
    jobs:
      - build-next-app:
          context: aws-deployment
